apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui-kit
  namespace: tools
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ui-kit
  template:
    metadata:
      labels:
        app: ui-kit
    spec:
      containers:
        - name: ui-kit
          image: docker.lending/ui-kit
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: ui-kit
  namespace: tools
  labels:
    app: ui-kit
spec:
  selector:
    app: ui-kit
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

---
kind: Middleware
apiVersion: traefik.containo.us/v1alpha1
metadata:
  name: ui-kit-redirect
  namespace: tools
spec:
  redirectScheme:
    scheme: https
    permanent: true

---
kind: IngressRoute
apiVersion: traefik.containo.us/v1alpha1
metadata:
  name: ui-kit
  namespace: tools
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`ui.lending.isb`)
      kind: Rule
      services:
        - name: ui-kit
          port: 80
      middlewares:
        - name: ui-kit-redirect

---
kind: IngressRoute
apiVersion: traefik.containo.us/v1alpha1
metadata:
  name: ui-kit
  namespace: tools
spec:
  entryPoints:
    - web-secure
  routes:
    - match: Host(`ui.lending.isb`)
      kind: Rule
      services:
        - name: ui-kit
          port: 80
  tls:
    passthrough: true
