import { COLORS } from '../docs'

const {
  TEXT_PRIMARY,
  TEXT_SECONDARY,
  TEXT_DISABLED,
  TEXT_INVERSE,
  TEXT_INVERSE_SECONDARY,
  TEXT_INVERSE_PRIMARY,
  PRIMARY,
  PRIMARY_HOVER,
  HIGHLIGHTED,
  ERROR,
  ERROR_HOVER,
  BLUE,
  BLUE_HOVER,
  BG_GREY_1,
  BG_GREY_2,
  BG_GREY_3,
  BG_GREY_4,
  COLOR_NOTIFICATION_SUCCESS,
} = COLORS

export const FILLS = {
  primary: TEXT_PRIMARY,
  secondary: TEXT_SECONDARY,
  disabled: TEXT_DISABLED,
  inverse: TEXT_INVERSE,
  green: PRIMARY,
  greenHover: PRIMARY_HOVER,
  highlighted: HIGHLIGHTED,
  danger: ERROR,
  dangerHover: ERROR_HOVER,
  blue: BLUE,
  blueHover: BLUE_HOVER,
  grey1: BG_GREY_1,
  grey2: BG_GREY_2,
  grey3: BG_GREY_3,
  grey4: BG_GREY_4,
  textInverseSecondary: TEXT_INVERSE_SECONDARY,
  textInversePrimary: TEXT_INVERSE_PRIMARY,
  darkGreen: COLOR_NOTIFICATION_SUCCESS,
}
